# ---------------------------------------------------
# Stage 1 - Build
# ---------------------------------------------------
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# ---------------------------------------------------
# Stage 2 - Production
# ---------------------------------------------------
FROM nginx:1.28-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

HEALTHCHECK \
    --interval=30s \
    --timeout=5s \
    --start-period=10s \
    --retries=3 \
    CMD wget --quiet --tries=1 --spider http://localhost || exit 1

CMD ["nginx","-g","daemon off;"]